export const API = 'API';
export const SET_USER_INFO = 'SET_USER_INFO';
export const TOGGLE_LOADER = 'TOGGLE_LOADER';
export const RESET_USER_INFO = 'RESET_USER_INFO';

export const SET_ALL_USER = 'SET_ALL_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const REMOVE_USER = 'REMOVE_USER';

export const SET_ALL_PRODUCT = 'SET_ALL_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';

export const SET_ALL_STORE = 'SET_ALL_STORE';
export const GET_STORE_BY_ID = 'GET_STORE_BY_ID';
export const CREATE_STORE = 'CREATE_STORE';
export const REMOVE_STORE = 'REMOVE_STORE';
export const UPDATE_STORE = 'UPDATE_STORE';

export const GET_CART_BY_USERID = 'GET_CART_BY_USERID';
export const GET_CART_DETAIL = 'GET_CART_DETAIL';
export const REMOVE_CART_BY_PRODUCT_ID = 'REMOVE_CART_BY_PRODUCT_ID';
export const UPDATE_CART_PRODUCT = 'UPDATE_CART_PRODUCT';

export const ADMIN_GET_PAYMENT = 'ADMIN_GET_PAYMENT';
export const ADMIN_ADD_PAYMENT = 'ADMIN_ADD_PAYMENT';
export const ADMIN_DELETE_PAYMENT = 'ADMIN_DELETE_PAYMENT';

export const ADMIN_GET_SHIPMENT = 'ADMIN_GET_SHIPMENT';
export const ADMIN_ADD_SHIPMENT = 'ADMIN_ADD_SHIPMENT';
export const ADMIN_DELETE_SHIPMENT = 'ADMIN_DELETE_SHIPMENT';

export const ADMIN_GET_NEW_SELLER = 'ADMIN_GET_NEW_SELLER';
export const ADMIN_GET_NEW_SELLER_DETAIL = 'ADMIN_GET_NEW_SELLER_DETAIL';
export const ADMIN_ACCEPT_NEW_SELLER = 'ADMIN_ACCEPT_NEW_SELLER';
export const ADMIN_REJECT_NEW_SELLER = 'ADMIN_REJECT_NEW_SELLER';