export const API = 'API';
export const SET_USER_INFO = 'SET_USER_INFO';
export const TOGGLE_LOADER = 'TOGGLE_LOADER';
export const RESET_USER_INFO = 'RESET_USER_INFO';

export const SET_ALL_USER = 'SET_ALL_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const REMOVE_USER = 'REMOVE_USER';

export const SET_ALL_PRODUCT = 'SET_ALL_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';

export const SET_ALL_STORE = 'SET_ALL_STORE';
export const GET_STORE_BY_ID = 'GET_STORE_BY_ID';
export const CREATE_STORE = 'CREATE_STORE';
export const REMOVE_STORE = 'REMOVE_STORE';
export const UPDATE_STORE = 'UPDATE_STORE';

export const GET_CART_BY_USERID = 'GET_CART_BY_USERID';
export const REMOVE_CART_BY_PRODUCT_ID = 'REMOVE_CART_BY_PRODUCT_ID';
export const UPDATE_CART_PRODUCT = 'UPDATE_CART_PRODUCT';